from tkinter import*
from tkinter import ttk
from tkinter import messagebox
a=Tk()
a.title("LOGIN PAGE")
p=PhotoImage(file="BMI.png")
l=Label(a,image=p)
l.place(relwidth=1,relheight=1)
L=Label(a,text="WELCOME TO OUR APP",bg="black",fg="white",font=("caliber",20))
L.pack(fill="x")
f=Frame(a,bd=10,bg="black")
l4=Label(a,text="LOGIN TO ENJOY OUR APP",bg="grey",font=("times",30))
l4.place(x=450,y=450)
l1=Label(f,text="USERNAME:",font=("times",10))
l1.grid(row=0,column=0,pady=3)
c=ttk.Combobox(f)
c["value"]=["DARSHAN","S"]
c.current(1)
c.grid(row=0,column=1,padx=3)
l2=Label(f,text="PASSWORD:",font=("times",10))
l2.grid(row=1,column=0,pady=3)
c1=ttk.Combobox(f)
c1["value"]=["12345","1"]
c1.current(1)
c1.grid(row=1,column=1,padx=3)
def login():
    if(c.get()=="S" and c1.get()=="1"):
        messagebox.showinfo("LOGIN","THANKYOU FOR LOGINING IN")
        d=Tk()
        d.title("DETAILS")
        d.geometry("350x350")
        d.config(bg="white")
        l2=Label(d,text="ENTER YOUR DETAILS CORRECTLY")
        l2.pack(fill="x")
        f1=Frame(d,bd=6,bg="black")
        f1.pack(pady=10)
        l32=Label(f1,text="GENDER:",bg="white")
        l32.grid(row=0,column=0,pady=5)
        C=ttk.Combobox(f1)
        C["value"]=["MALE","FEMALE","OTHERS"]
        C.grid(row=0,column=1,padx=3)
        l3=Label(f1,text="YOUR WEIGHT(in kg):",bg="white")
        l3.grid(row=1,column=0,pady=5)
        e=Entry(f1)
        e.grid(row=1,column=1,padx=3)
        l5=Label(f1,text="YOUR HEIGHT(in cm):",bg="white")
        l5.grid(row=2,column=0,pady=5)
        e1=Entry(f1)
        e1.grid(row=2,column=1,padx=3)
        def m():
            r=(float(e1.get())/100)
            e2.insert(0,r)
        l7=Label(f1,text="CLICK:",bg="light blue")
        l7.grid(row=3,column=0,pady=5)
        b=Button(f1,text="YOUR HEIGHT(in m):",bg="light blue",command=m)
        b.grid(row=4,column=0)
        e2=Entry(f1)
        e2.grid(row=4,column=1)
        def BMI():
            y=(float(e.get()))/((float(e2.get()))*(float(e2.get())))
            e21.insert(0,y)
        l71=Label(f1,text="CLICK:",bg="pink")
        l71.grid(row=5,column=0,pady=5)
        b2=Button(f1,text="YOUR BMI:",bg="pink",command=BMI)
        b2.grid(row=6,column=0)
        e21=Entry(f1)
        e21.grid(row=6,column=1)
        def submit():
            q=float(e21.get())
            if((q>=0)and(q<18.25)):
                v=Tk()
                v.config(bg="black")
                l=Label(v,text="YOUR BMI IS UNDERWEIGHT",bg="pink",font=("times",50))
                l.pack()
                f2=Frame(v)
                f2.pack()
                L=Label(f2,text="                                                                                                       ",bg="pink")
                L.grid(row=0,column=0)
                def suggest():
                    h=Tk()
                    h.title("SUGGESTION")
                    h.config(bg="black")
                    l3=Label(h,text="FOLLOW THIS AND IMPROVE TO NORMAL BMI: ",bg="grey",font=("caliber",20))
                    l3.pack(fill="x")
                    l4=Label(h,text="1.EAT FREQUENTLY",font=("times",20))
                    l4.pack(fill="x")
                    l9=Label(h,text="2.ADD PROTEIN IN YOUR DIET",font=("times",20))
                    l9.pack(fill="x")
                    l94=Label(h,text="3.GO TO GYM",font=("times",20))
                    l94.pack(fill="x")
                    l91=Label(h,text="4.EAT MORE CALORIES",font=("times",20))
                    l91.pack(fill="x")
                    l93=Label(h,text="IF YOU WANT TO KNOW ABOUT DIET PLAN CLICK THE BELOW BUTTON",bg="pink",font=("caliber",20))
                    l93.pack(fill="x")
                    def diet():
                        o=Tk()
                        o.title("DIET")
                        o.config(bg="BLACK")
                        f3=Frame(o)
                        f3.grid(row=0,column=0)
                        l=Label(f3,text="BREAKFAST:",bg="pink",font=("times",30))
                        l.grid(row=0,column=0)
                        f4=Frame(o)
                        f4.grid(row=1,column=7)
                        l1=Label(f4,text="#EAT OLD RICE WITH HONEY ",font=("times",20))
                        l1.pack()
                        l2=Label(f4,text="#ADD VEGETABLES IN YOUR DIET ",font=("times",20))
                        l2.pack()
                        l3=Label(f4,text="#ADD DRY FRUITS",font=("times",20))
                        l3.pack()
                        l4=Label(f4,text="#ADD BANANA",font=("times",20))
                        l4.pack()
                        l5=Label(f4,text="#ADD EGGS(2)/ADD PANEER",font=("times",20))
                        l5.pack()
                        f5=Frame(o)
                        f5.grid(row=2,column=0)
                        l6=Label(f5,text="LUNCH:",bg="ORANGE",font=("times",30))
                        l6.grid(row=0,column=0)
                        f41=Frame(o)
                        f41.grid(row=3,column=7)
                        l11=Label(f41,text="#EAT RICE WITH VEGETABLES ",font=("times",20))
                        l11.pack()
                        l21=Label(f41,text="#ADD PROTEIN RICH ITEMS ",font=("times",20))
                        l21.pack()
                        l31=Label(f41,text="#ADD CURD",font=("times",20))
                        l31.pack()
                        l41=Label(f41,text="#ADD BANANA",font=("times",20))
                        l41.pack()
                        l51=Label(f41,text="#ADD OMLET/ADD PANEER",font=("times",20))
                        l51.pack()
                        l52=Label(f41,text="#ADD GROUNDNUT(100g)",font=("times",20))
                        l52.pack()
                        l54=Label(f41,text="#ADD SWEET POTATO",font=("times",20))
                        l54.pack()
                        f51=Frame(o)
                        f51.grid(row=4,column=0)
                        l61=Label(f51,text="DINNER:",bg="VIOLET",font=("times",30))
                        l61.grid(row=0,column=0)
                        f42=Frame(o)
                        f42.grid(row=5,column=7)
                        l12=Label(f42,text="#ADD DOSA",font=("times",20))
                        l12.pack()
                        l22=Label(f42,text="#ADD VEGETABLES",font=("times",20))
                        l22.pack()
                        l32=Label(f42,text="#ADD MILK",font=("times",20))
                        l32.pack()
                        l42=Label(f42,text="#ADD BANANA",font=("times",20))
                        l42.pack()
                        
                        
                    b=Button(h,text="DIET",bg='violet',font=("caliber",30),command=diet)
                    b.pack()
                             
                l7=Label(f2,text="CLICK:",bg="light blue")
                l7.grid(row=0,column=1)    
                b1=Button(f2,text="SUGGESTION",bg="YELLOW",command=suggest)
                b1.grid(row=0,column=2)
                L=Label(f2,text="                                                                                                       ",bg="pink")
                L.grid(row=0,column=3)
            if((q>=18.25)and(q<25)):
                v=Tk()
                v.config(bg="black")
                v.title("BMI")
                l=Label(v,text="YOUR BMI IS NORMAL",bg="orange",font=("caliber",50))
                l.pack()
                f2=Frame(v)
                f2.pack()
                L=Label(f2,text="                                                                        ",bg="orange")
                L.grid(row=0,column=0)
                def suggest():
                    h=Tk()
                    h.title("SUGGESTION")
                    h.config(bg="black")
                    l3=Label(h,text="FOLLOW THIS TO MAINTAIN NORMAL BMI: ",bg="grey",font=("caliber",20))
                    l3.pack(fill="x")
                    l4=Label(h,text="1.MAINTAIN YOUR WEIGHT",font=("times",20))
                    l4.pack(fill="x")
                    l9=Label(h,text="2.ADD PROTEIN IN YOUR DIET",font=("times",20))
                    l9.pack(fill="x")
                    l94=Label(h,text="3.GO TO GYM TO MAINTAIN",font=("times",20))
                    l94.pack(fill="x")
                    l91=Label(h,text="4.EAT ONLY IF YOU NEED",font=("times",20))
                    l91.pack(fill="x")
                    l93=Label(h,text="IF YOU WANT TO KNOW ABOUT DIET PLAN CLICK THE BELOW BUTTON",bg="pink",font=("caliber",20))
                    l93.pack(fill="x")
                    def diet():
                        o=Tk()
                        o.title("DIET")
                        o.config(bg="BLACK")
                        f3=Frame(o)
                        f3.grid(row=0,column=0)
                        l=Label(f3,text="BREAKFAST:",bg="pink",font=("times",30))
                        l.grid(row=0,column=0)
                        f4=Frame(o)
                        f4.grid(row=1,column=7)
                        l1=Label(f4,text="#EAT OLD RICE WITH HONEY ",font=("times",20))
                        l1.pack()
                        l2=Label(f4,text="#ADD VEGETABLES IN YOUR DIET ",font=("times",20))
                        l2.pack()
                        l3=Label(f4,text="#ADD DRY FRUITS",font=("times",20))
                        l3.pack()
                        l4=Label(f4,text="#ADD BANANA",font=("times",20))
                        l4.pack()
                        l5=Label(f4,text="#ADD EGGS(2)/ADD PANEER",font=("times",20))
                        l5.pack()
                        f5=Frame(o)
                        f5.grid(row=2,column=0)
                        l6=Label(f5,text="LUNCH:",bg="ORANGE",font=("times",30))
                        l6.grid(row=0,column=0)
                        f41=Frame(o)
                        f41.grid(row=3,column=7)
                        l11=Label(f41,text="#EAT RICE WITH VEGETABLES ",font=("times",20))
                        l11.pack()
                        l21=Label(f41,text="#ADD PROTEIN RICH ITEMS ",font=("times",20))
                        l21.pack()
                        l31=Label(f41,text="#ADD CURD",font=("times",20))
                        l31.pack()
                        l41=Label(f41,text="#ADD BANANA",font=("times",20))
                        l41.pack()
                        l51=Label(f41,text="#ADD OMLET/ADD PANEER",font=("times",20))
                        l51.pack()
                        l52=Label(f41,text="#ADD GROUNDNUT(100g)",font=("times",20))
                        l52.pack()
                        l54=Label(f41,text="#ADD SWEET POTATO",font=("times",20))
                        l54.pack()
                        f51=Frame(o)
                        f51.grid(row=4,column=0)
                        l61=Label(f51,text="DINNER:",bg="VIOLET",font=("times",30))
                        l61.grid(row=0,column=0)
                        f42=Frame(o)
                        f42.grid(row=5,column=7)
                        l12=Label(f42,text="#ADD DOSA",font=("times",20))
                        l12.pack()
                        l22=Label(f42,text="#ADD VEGETABLES",font=("times",20))
                        l22.pack()
                        l32=Label(f42,text="#ADD MILK",font=("times",20))
                        l32.pack()
                        l42=Label(f42,text="#ADD BANANA",font=("times",20))
                        l42.pack()
                        
                    b=Button(h,text="DIET",bg='violet',font=("caliber",30),command=diet)
                    b.pack()
                l7=Label(f2,text="CLICK:",bg="light blue")
                l7.grid(row=0,column=1)             
                b1=Button(f2,text="SUGGESTION",bg="YELLOW",command=suggest)
                b1.grid(row=0,column=2)
                L=Label(f2,text="                                                                         ",bg="orange")
                L.grid(row=0,column=3)
            if(q>=25):
                v56=Tk()
                v56.config(bg="black")
                l66=Label(v56,text="YOUR BMI IS OVERWEIGHT",bg="red",font=("times",50))
                l66.pack()
                f2=Frame(v56)
                f2.pack()
                L=Label(f2,text="                                                                            ",bg="red")
                L.grid(row=0,column=0)
                def suggest():
                    h=Tk()
                    h.title("SUGGESTION")
                    h.config(bg="black")
                    l3=Label(h,text="FOLLOW THIS AND IMPROVE TO NORMAL BMI: ",bg="grey",font=("caliber",20))
                    l3.pack(fill="x")
                    l4=Label(h,text="1.DO PHYSICAL ACTIVITIES",font=("times",20))
                    l4.pack(fill="x")
                    l9=Label(h,text="2.MAINTAIN A PROPER DIET",font=("times",20))
                    l9.pack(fill="x")
                    l94=Label(h,text="3.GO TO GYM",font=("times",20))
                    l94.pack(fill="x")
                    l91=Label(h,text="4.LEAVE YOUR TUMMY EMPTY FOR DAYS",font=("times",20))
                    l91.pack(fill="x")
                    l93=Label(h,text="IF YOU WANT TO KNOW ABOUT DIET PLAN CLICK THE BELOW BUTTON",bg="pink",font=("caliber",20))
                    l93.pack(fill="x")
                    def diet():
                        o=Tk()
                        o.title("DIET")
                        o.config(bg="BLACK")
                        f3=Frame(o)
                        f3.grid(row=0,column=0)
                        l=Label(f3,text="BREAKFAST:",bg="pink",font=("times",30))
                        l.grid(row=0,column=0)
                        f4=Frame(o)
                        f4.grid(row=1,column=7)
                        l1=Label(f4,text="#EAT ONLY LESS(IF POSSIBLE AVOID) ",font=("times",20))
                        l1.pack()
                        f5=Frame(o)
                        f5.grid(row=2,column=0)
                        l6=Label(f5,text="LUNCH:",bg="ORANGE",font=("times",30))
                        l6.grid(row=0,column=0)
                        f41=Frame(o)
                        f41.grid(row=3,column=7)
                        l11=Label(f41,text="#EAT RICE WITH VEGETABLES(100g) ",font=("times",20))
                        l11.pack()
                        l21=Label(f41,text="#ADD PROTEIN RICH ITEMS ",font=("times",20))
                        l21.pack()
                        l51=Label(f41,text="#ADD OMLET/ADD PANEER",font=("times",20))
                        l51.pack()
                        l52=Label(f41,text="#ADD GROUNDNUT(100g)",font=("times",20))
                        l52.pack()
                        l54=Label(f41,text="#ADD SWEET POTATO",font=("times",20))
                        l54.pack()
                        f51=Frame(o)
                        f51.grid(row=4,column=0)
                        l61=Label(f51,text="DINNER:",bg="VIOLET",font=("times",30))
                        l61.grid(row=0,column=0)
                        f42=Frame(o)
                        f42.grid(row=5,column=7)
                        l12=Label(f42,text="#ADD CHAPATTI",font=("times",20))
                        l12.pack()
                        l22=Label(f42,text="#ADD VEGETABLES",font=("times",20))
                        l22.pack()
                        l32=Label(f42,text="#ADD MILk",font=("times",20))
                        l32.pack()
                        l42=Label(f42,text="#ADD BANANA",font=("times",20))
                        l42.pack()
                        
                    b=Button(h,text="DIET",bg='violet',font=("caliber",30),command=diet)
                    b.pack()
                l7=Label(f2,text="CLICK:",bg="light blue")
                l7.grid(row=0,column=1)             
                b1=Button(f2,text="SUGGESTION",bg="YELLOW",command=suggest)
                b1.grid(row=0,column=2)
                L=Label(f2,text="                                                                           ",bg="red")
                L.grid(row=0,column=3)
        b1=Button(d,text="SUBMIT",bg="green",command=submit)
        b1.pack()
        
    else:
        messagebox.showinfo("404 ERROR","PLS ENTER CORRECTLY TO ENJOY")
        
b=Button(f,text="LOGIN",bg="green",font=("times",10),command=login)
b.grid(row=3,column=1)
f.place(y=500,x=500)
